module.exports.allCategories = [
    { name: "All", icon: "📋" },
    { name: "Amazing views", icon: "👁️" },
    { name: "Art Deco", icon: "🏛️" },
    { name: "Asian culture", icon: "🏮" },
    { name: "Adventure", icon: "🧗" },
    { name: "Beachfront", icon: "🏖️" },
    { name: "Brownstones", icon: "💍" },
    { name: "Business travel", icon: "💼" },
    { name: "Cabins", icon: "🏘️" },
    { name: "Canals", icon: "🛥️" },
    { name: "Castles", icon: "🏰" },
    { name: "Chalets", icon: "🏔️" },
    { name: "Coastal", icon: "🌊" },
    { name: "Cottages", icon: "🏡" },
    { name: "Countryside", icon: "🌾" },
    { name: "Design", icon: "🎨" },
    { name: "Desert", icon: "🏜️" },
    { name: "Earth homes", icon: "🌍" },
    { name: "Eco-friendly", icon: "🌱" },
    { name: "Fishing", icon: "🎣" },
    { name: "Gardens", icon: "🌺" },
    { name: "Historic homes", icon: "🏛️" },
    { name: "Islands", icon: "🏝️" },
    { name: "Lakefront", icon: "🏞️" },
    { name: "Luxe", icon: "💎" },
    { name: "Mansions", icon: "🏰" },
    { name: "Mediterranean", icon: "🫒" },
    { name: "Mountains", icon: "⛰️" },
    { name: "National parks", icon: "🌲" },
    { name: "OMG!", icon: "😱" },
    { name: "Off-the-grid", icon: "🔌" },
    { name: "Overwater", icon: "🌊" },
    { name: "Party", icon: "🎉" },
    { name: "Penthouses", icon: "🏢" },
    { name: "Pools", icon: "🏊" },
    { name: "Private", icon: "🔒" },
    { name: "Romantic", icon: "💕" },
    { name: "Rustic", icon: "🪵" },
    { name: "Safari", icon: "🦁" },
    { name: "Secluded", icon: "🤫" },
    { name: "Ski-in/out", icon: "⛷️" },
    { name: "Southern charm", icon: "🌺" },
    { name: "Surfing", icon: "🏄" },
    { name: "Treehouses", icon: "🌳" },
    { name: "Trending", icon: "📈" },
    { name: "Tropical", icon: "🌴" },
    { name: "Unique stays", icon: "✨" },
    { name: "Urban", icon: "🏙️" },
    { name: "Villas", icon: "🏖️" },
    { name: "Vineyards", icon: "🍇" },
    { name: "Wildlife", icon: "🦒" },
    { name: "Winter sports", icon: "🎿" },
    { name: "Yoga retreats", icon: "🧘" },
    { name: "Others", icon: "⺟" },
];

module.exports.categories = [
    "Beachfront",
    "Amazing views",
    "Romantic",
    "Coastal",
    "Design",
    "Urban",
    "Trending",
    "Business travel",
    "Cabins",
    "Off-the-grid",
    "Mountains",
    "Mansions",
    "Historic homes",
    "Luxe",
    "Vineyards",
    "Countryside",
    "OMG!",
    "Treehouses",
    "Earth homes",
    "Unique stays",
    "Tropical",
    "Pools",
    "Lakefront",
    "Fishing",
    "Penthouses",
    "Ski-in/out",
    "Winter sports",
    "Safari",
    "Wildlife",
    "Adventure",
    "Canals",
    "Islands",
    "Private",
    "Cottages",
    "Brownstones",
    "Yoga retreats",
    "National parks",
    "Art Deco",
    "Party",
    "Villas",
    "Castles",
    "Desert",
    "Rustic",
    "Mediterranean",
    "Eco-friendly",
    "Gardens",
    "Southern charm",
    "Asian culture",
    "Overwater",
    "Chalets",
    "Surfing",
    "Secluded",
    "Others",
];
